### ISSUE TITLE
Add Swift Package Manager manifest

### ISSUE THREAD

**Issue by romeouald** [Coder-ZJQ/JQCollectionViewAlignLayout#1]
It would be nice to have SPM support

**Comment by Coder-ZJQ** [comment]
Sorry for the delay of reply. I have added the Swift Package Manager manifest on version 0.2.2. Hope you can enjoy it. ：）
![image](https://user-images.githubusercontent.com/15013685/104567836-3b949180-568a-11eb-83f7-07e551a98d06.png)
